# Generated by Django 3.0.8 on 2020-09-29 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_invitation_rang"),
    ]

    operations = [
        migrations.CreateModel(
            name="GebruikersRang",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rang", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="invitation",
            name="rang",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.GebruikersRang",
            ),
        ),
    ]
