# Generated by Django 3.0.8 on 2020-09-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200929_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='rang',
            field=models.CharField(choices=[('SOG', 'Syntrus Projectmanager'), ('SD', 'Derde')], default='SD', max_length=3),
        ),
        migrations.DeleteModel(
            name='GebruikersRang',
        ),
    ]
