# Generated by Django 3.0.8 on 2020-12-01 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0027_auto_20201118_1407'),
        ('users', '0011_auto_20201201_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentcheckinvitation',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
    ]
