# Generated by Django 3.0.8 on 2021-01-21 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_commentcheckinvitation_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisatie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='commentcheckinvitation',
            name='user_afdeling',
        ),
        migrations.RemoveField(
            model_name='commentcheckinvitation',
            name='user_functie',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='afdeling',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='functie',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='omschrijving',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='user_afdeling',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='user_functie',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='type_user',
            field=models.CharField(choices=[('B', 'Beheerder'), ('SB', 'Syntrus Beheerder'), ('SOG', 'Syntrus Projectmanager'), ('SD', 'Syntrus Derden')], default='SD', max_length=3),
        ),
        migrations.AddField(
            model_name='commentcheckinvitation',
            name='organisatie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Organisatie'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='organisatie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Organisatie'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='organisatie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Organisatie'),
        ),
    ]
