# Generated by Django 3.0.8 on 2021-01-21 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_auto_20210121_1512"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commentcheckinvitation",
            name="organisatie",
        ),
        migrations.RemoveField(
            model_name="commentcheckinvitation",
            name="project",
        ),
        migrations.AlterField(
            model_name="commentcheckinvitation",
            name="invitee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitee",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
