# Generated by Django 3.0.8 on 2021-01-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0033_project_organisaties'),
        ('users', '0015_organisatie_gebruikers'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisatie',
            name='projecten',
            field=models.ManyToManyField(default=None, related_name='projecten', to='project.Project'),
        ),
    ]
