# Generated by Django 3.0.8 on 2021-01-25 16:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_organisatie_projecten"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="last_visit",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="last visit"
            ),
        ),
    ]
