# Generated by Django 3.0.8 on 2021-01-25 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0034_auto_20210125_1808'),
        ('users', '0017_customuser_last_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='organisatie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Organisatie'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
    ]
