# Generated by Django 3.1.12 on 2021-10-14 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0040_auto_20211014_1426'),
        ('users', '0019_forgotpassinvite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='organisatie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='users.organisatie'),
        ),
        migrations.AlterField(
            model_name='organisatie',
            name='gebruikers',
            field=models.ManyToManyField(default=None, related_name='in_organisatie', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organisatie',
            name='projecten',
            field=models.ManyToManyField(default=None, related_name='in_organisatie', to='project.Project'),
        ),
    ]
