# Generated by Django 3.1.12 on 2021-10-14 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0041_auto_20211014_1451'),
        ('users', '0020_auto_20211014_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='klantenorganisatie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.beleggers'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='type_user',
            field=models.CharField(choices=[('B', 'Beheerder'), ('SB', 'Klant Beheerder'), ('SOG', 'Projectmanager'), ('SD', 'Derden')], default='SD', max_length=3),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='rang',
            field=models.CharField(choices=[('SOG', 'Projectmanager'), ('SD', 'Derde')], default='SD', max_length=3),
        ),
    ]
