# Generated by Django 3.1.12 on 2021-10-15 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0041_auto_20211014_1451'),
        ('users', '0021_auto_20211014_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='klantenorganisatie',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='werknemer', to='project.beleggers'),
        ),
        migrations.AddField(
            model_name='organisatie',
            name='klantenorganisatie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisatie', to='project.beleggers'),
        ),
    ]
