# Generated by Django 3.1.12 on 2021-10-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20211020_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisatie',
            name='naam',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
