# Generated by Django 3.1.12 on 2021-12-03 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0044_pveitemannotation_firststatus'),
        ('users', '0025_auto_20211020_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='klantenorganisatie',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='werknemer', to='project.beleggers'),
        ),
    ]
