# Generated by Django 3.1.12 on 2021-12-08 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0045_auto_20211208_1304'),
        ('users', '0026_auto_20211203_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='organisatie',
            new_name='stakeholder',
        ),
        migrations.RenameField(
            model_name='invitation',
            old_name='klantenorganisatie',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='invitation',
            old_name='organisatie',
            new_name='stakeholder',
        ),
        migrations.RenameField(
            model_name='organisatie',
            old_name='naam',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='organisatie',
            old_name='gebruikers',
            new_name='users',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='klantenorganisatie',
        ),
        migrations.RemoveField(
            model_name='organisatie',
            name='klantenorganisatie',
        ),
        migrations.AddField(
            model_name='customuser',
            name='client',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to='project.beleggers'),
        ),
        migrations.AddField(
            model_name='organisatie',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stakeholder', to='project.beleggers'),
        ),
    ]
