# Generated by Django 2.2.7 on 2020-03-25 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200325_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pveitem',
            name='inhoudonderdeel',
        ),
        migrations.RemoveField(
            model_name='pveitem',
            name='onderdeel',
        ),
        migrations.AddField(
            model_name='pvesectie',
            name='inhoudonderdeel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.PVEInhoudOnderdeel'),
        ),
        migrations.AddField(
            model_name='pvesectie',
            name='onderdeel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.PVEOnderdeel'),
        ),
    ]
