# Generated by Django 2.2.7 on 2020-03-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200325_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pveitem',
            name='bijlage',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='pvesectie',
            name='STABUhoofdstuk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pvesectie',
            name='STABUnaam',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='pvesectie',
            name='STABUparagraaf',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='pvesectie',
            name='hoofdstuk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pvesectie',
            name='paragraaf',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pvesectie',
            name='subparagraaf',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
