# Generated by Django 3.0.8 on 2020-09-03 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_auto_20200902_1342"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pveitem",
            name="bijlage",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
