# Generated by Django 2.2.7 on 2020-03-25 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200325_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='PVEHoofdstuk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoofdstuk', models.CharField(blank=True, max_length=256, null=True)),
                ('onderdeel', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.PVEOnderdeel')),
            ],
        ),
        migrations.CreateModel(
            name='PVEParagraaf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraaf', models.CharField(blank=True, max_length=256, null=True)),
                ('hoofdstuk', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.PVEHoofdstuk')),
            ],
        ),
        migrations.CreateModel(
            name='PVESubparagraaf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subparagraaf', models.CharField(blank=True, max_length=256, null=True)),
                ('bijlage', models.FileField(blank=True, null=True, upload_to='')),
                ('sectie', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.PVEParagraaf')),
            ],
        ),
        migrations.CreateModel(
            name='STABUHoofdstuk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoofdstukSTABU', models.IntegerField(blank=True, max_length=256, null=True)),
                ('benaming', models.CharField(blank=True, max_length=256, null=True)),
                ('hoofdstukPVE', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.PVEHoofdstuk')),
            ],
        ),
        migrations.CreateModel(
            name='STABUParagraaf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraafSTABU', models.CharField(blank=True, max_length=256, null=True)),
                ('paragraafPVE', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.PVEParagraaf')),
            ],
        ),
        migrations.RemoveField(
            model_name='pvesectie',
            name='inhoudonderdeel',
        ),
        migrations.RemoveField(
            model_name='pvesectie',
            name='onderdeel',
        ),
        migrations.RemoveField(
            model_name='pveitem',
            name='sectie',
        ),
        migrations.DeleteModel(
            name='PVEInhoudOnderdeel',
        ),
        migrations.DeleteModel(
            name='PVESectie',
        ),
        migrations.AddField(
            model_name='pveitem',
            name='sectiePVE',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.PVEParagraaf'),
        ),
        migrations.AddField(
            model_name='pveitem',
            name='sectieSTABU',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.STABUParagraaf'),
        ),
    ]
