# Generated by Django 2.2.7 on 2020-03-25 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200325_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='stabuparagraaf',
            name='hoofdstukPVE',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.PVEHoofdstuk'),
        ),
        migrations.AddField(
            model_name='stabuparagraaf',
            name='hoofdstukSTABU',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.STABUHoofdstuk'),
        ),
        migrations.AlterField(
            model_name='pveitem',
            name='sectiePVE',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.PVEParagraaf'),
        ),
        migrations.AlterField(
            model_name='pveitem',
            name='sectieSTABU',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.STABUParagraaf'),
        ),
        migrations.AlterField(
            model_name='stabuparagraaf',
            name='paragraafPVE',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.PVEParagraaf'),
        ),
    ]
