# Generated by Django 3.0.8 on 2020-09-03 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_invites'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invites',
        ),
    ]
