# Generated by Django 2.2.7 on 2020-03-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200325_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bouwsoort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Doelgroep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='TypeObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='pveitem',
            name='parameters',
        ),
        migrations.AddField(
            model_name='pveitem',
            name='AED',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pveitem',
            name='EntreeUpgrade',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pveitem',
            name='JamesConcept',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pveitem',
            name='Pakketdient',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pveitem',
            name='Smarthome',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PVEParameters',
        ),
        migrations.AddField(
            model_name='pveitem',
            name='Bouwsoort',
            field=models.ManyToManyField(to='app.Bouwsoort'),
        ),
        migrations.AddField(
            model_name='pveitem',
            name='Doelgroep',
            field=models.ManyToManyField(to='app.Doelgroep'),
        ),
        migrations.AddField(
            model_name='pveitem',
            name='TypeObject',
            field=models.ManyToManyField(to='app.TypeObject'),
        ),
    ]
