# Generated by Django 3.0.8 on 2020-09-22 13:46

import functools

from django.db import migrations, models

import utils.upload_rename


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_delete_invites"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pveitem",
            name="bijlage",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=functools.partial(
                    utils.upload_rename._update_filename,
                    *(),
                    **{"path": "BasisBijlages"}
                ),
            ),
        ),
    ]
