# Generated by Django 3.0.8 on 2020-11-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_auto_20200922_1546"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pveitem",
            name="bijlage",
            field=models.FileField(blank=True, null=True, upload_to="BasisBijlages/"),
        ),
    ]
