# Generated by Django 2.2.7 on 2020-03-26 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200326_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pveitem',
            name='Bouwsoort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Bouwsoort'),
        ),
        migrations.AlterField(
            model_name='pveitem',
            name='Doelgroep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Doelgroep'),
        ),
        migrations.AlterField(
            model_name='pveitem',
            name='TypeObject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.TypeObject'),
        ),
    ]
