# Generated by Django 3.1.7 on 2021-03-03 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_auto_20210303_1902"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pvehoofdstuk",
            name="onderdeel",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.pveonderdeel",
            ),
        ),
    ]
