# Generated by Django 2.2.7 on 2020-03-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200326_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pveitem',
            name='Bouwsoort',
        ),
        migrations.AddField(
            model_name='pveitem',
            name='Bouwsoort',
            field=models.ManyToManyField(to='app.Bouwsoort'),
        ),
        migrations.RemoveField(
            model_name='pveitem',
            name='Doelgroep',
        ),
        migrations.AddField(
            model_name='pveitem',
            name='Doelgroep',
            field=models.ManyToManyField(to='app.Doelgroep'),
        ),
        migrations.RemoveField(
            model_name='pveitem',
            name='TypeObject',
        ),
        migrations.AddField(
            model_name='pveitem',
            name='TypeObject',
            field=models.ManyToManyField(to='app.TypeObject'),
        ),
    ]
