# Generated by Django 3.1.7 on 2021-03-03 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0036_auto_20210204_1847"),
        ("app", "0012_auto_20210303_1909"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActieveVersie",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "belegger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.beleggers",
                    ),
                ),
                (
                    "versie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.pveversie"
                    ),
                ),
            ],
        ),
    ]
