# Generated by Django 2.2.7 on 2020-03-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200327_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pveitem',
            name='Bouwsoort',
            field=models.ManyToManyField(blank=True, to='app.Bouwsoort'),
        ),
        migrations.AlterField(
            model_name='pveitem',
            name='Doelgroep',
            field=models.ManyToManyField(blank=True, to='app.Doelgroep'),
        ),
        migrations.AlterField(
            model_name='pveitem',
            name='TypeObject',
            field=models.ManyToManyField(blank=True, to='app.TypeObject'),
        ),
    ]
