# Generated by Django 3.1.7 on 2021-05-22 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_actieveversie'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemBijlage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bijlage', models.FileField(blank=True, null=True, upload_to='BasisBijlages')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pveitem')),
            ],
        ),
    ]
