# Generated by Django 2.2.7 on 2020-04-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200327_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pveitem',
            name='inhoud',
            field=models.TextField(max_length=5000),
        ),
    ]
