# Generated by Django 2.2.7 on 2020-04-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200406_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pveitem',
            name='bijlage',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
