# Generated by Django 3.1.7 on 2021-08-02 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210522_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='itembijlages',
            name='versie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.pveversie'),
        ),
        migrations.DeleteModel(
            name='ItemBijlage',
        ),
    ]
