# Generated by Django 3.1.7 on 2021-08-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210802_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='itembijlages',
            name='naam',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
