# Generated by Django 2.2.7 on 2020-04-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200407_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pveitem',
            name='bijlage',
            field=models.FileField(blank=True, null=True, upload_to='attachments/%Y/%m/%d/'),
        ),
    ]
