# Generated by Django 2.2.7 on 2020-04-08 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20200407_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stabuparagraaf',
            name='hoofdstukPVE',
        ),
        migrations.RemoveField(
            model_name='stabuparagraaf',
            name='hoofdstukSTABU',
        ),
        migrations.RemoveField(
            model_name='stabuparagraaf',
            name='paragraafPVE',
        ),
        migrations.AlterField(
            model_name='pveitem',
            name='sectieSTABU',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='STABUHoofdstuk',
        ),
        migrations.DeleteModel(
            name='STABUParagraaf',
        ),
    ]
