# Generated by Django 2.2.7 on 2020-04-10 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20200408_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pveitem',
            name='sectieSTABU',
        ),
        migrations.AlterField(
            model_name='pveitem',
            name='sectiePVE',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.PVEParagraaf'),
        ),
    ]
