# Generated by Django 3.1.12 on 2021-10-14 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0039_bijlagetoannotation_naam'),
        ('app', '0018_auto_20210811_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actieveversie',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='bouwsoort',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='doelgroep',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='itembijlages',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='pvehoofdstuk',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='pveitem',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='pveonderdeel',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='pveparagraaf',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='pveversie',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='typeobject',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='actieveversie',
            name='belegger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actieve_versie', to='project.beleggers'),
        ),
        migrations.AlterField(
            model_name='actieveversie',
            name='versie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actieve_versie', to='app.pveversie'),
        ),
        migrations.AlterField(
            model_name='bouwsoort',
            name='versie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bouwsoort', to='app.pveversie'),
        ),
        migrations.AlterField(
            model_name='doelgroep',
            name='versie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doelgroep', to='app.pveversie'),
        ),
        migrations.AlterField(
            model_name='itembijlages',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='itembijlage', to='app.PVEItem'),
        ),
        migrations.AlterField(
            model_name='itembijlages',
            name='versie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itembijlage', to='app.pveversie'),
        ),
        migrations.AlterField(
            model_name='pvehoofdstuk',
            name='onderdeel',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hoofdstuk', to='app.pveonderdeel'),
        ),
        migrations.AlterField(
            model_name='pvehoofdstuk',
            name='versie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hoofdstuk', to='app.pveversie'),
        ),
        migrations.AlterField(
            model_name='pveitem',
            name='Bouwsoort',
            field=models.ManyToManyField(blank=True, related_name='item', to='app.Bouwsoort'),
        ),
        migrations.AlterField(
            model_name='pveitem',
            name='Doelgroep',
            field=models.ManyToManyField(blank=True, related_name='item', to='app.Doelgroep'),
        ),
        migrations.AlterField(
            model_name='pveitem',
            name='TypeObject',
            field=models.ManyToManyField(blank=True, related_name='item', to='app.TypeObject'),
        ),
        migrations.AlterField(
            model_name='pveitem',
            name='hoofdstuk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='app.pvehoofdstuk'),
        ),
        migrations.AlterField(
            model_name='pveitem',
            name='paragraaf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='app.pveparagraaf'),
        ),
        migrations.AlterField(
            model_name='pveitem',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='item', to='project.Project'),
        ),
        migrations.AlterField(
            model_name='pveitem',
            name='versie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='app.pveversie'),
        ),
        migrations.AlterField(
            model_name='pveparagraaf',
            name='hoofdstuk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='paragraaf', to='app.pvehoofdstuk'),
        ),
        migrations.AlterField(
            model_name='pveparagraaf',
            name='versie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paragraaf', to='app.pveversie'),
        ),
        migrations.AlterField(
            model_name='pveversie',
            name='belegger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versie', to='project.beleggers'),
        ),
        migrations.AlterField(
            model_name='typeobject',
            name='versie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='typeobject', to='app.pveversie'),
        ),
    ]
