# Generated by Django 2.2.7 on 2020-04-10 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20200410_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pveitem',
            name='sectiePVE',
        ),
        migrations.AddField(
            model_name='pveitem',
            name='hoofdstuk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.PVEHoofdstuk'),
        ),
        migrations.AddField(
            model_name='pveitem',
            name='paragraaf',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.PVEParagraaf'),
        ),
    ]
