# Generated by Django 3.1.12 on 2021-10-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20211014_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='pveversie',
            name='public',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
