# Generated by Django 2.2.7 on 2020-04-10 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20200410_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pveitem',
            old_name='paragraaf',
            new_name='sectiePVE',
        ),
    ]
