# Generated by Django 3.1.12 on 2021-10-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20211020_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(blank=True, choices=[('P', 'Project'), ('K', 'Klant'), ('PvE', 'PvE')], max_length=5, null=True)),
                ('update', models.CharField(blank=True, max_length=500, null=True)),
                ('datum', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
