# Generated by Django 2.2.7 on 2020-04-10 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20200410_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pveitem',
            old_name='sectiePVE',
            new_name='paragraaf',
        ),
    ]
