# Generated by Django 2.2.7 on 2020-04-15 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20200410_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pveitem',
            name='paragraaf',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.PVEParagraaf'),
        ),
    ]
