# Generated by Django 3.1.12 on 2021-11-02 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_activity_schuldige'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-datum']},
        ),
    ]
