# Generated by Django 3.1.12 on 2021-12-08 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0045_auto_20211208_1304'),
        ('app', '0024_auto_20211102_1721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='actieveversie',
            old_name='belegger',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='actieveversie',
            old_name='versie',
            new_name='version',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='datum',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='bouwsoort',
            old_name='versie',
            new_name='version',
        ),
        migrations.RenameField(
            model_name='doelgroep',
            old_name='versie',
            new_name='version',
        ),
        migrations.RenameField(
            model_name='itembijlages',
            old_name='bijlage',
            new_name='attachment',
        ),
        migrations.RenameField(
            model_name='itembijlages',
            old_name='naam',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='pvehoofdstuk',
            old_name='hoofdstuk',
            new_name='chapter',
        ),
        migrations.RenameField(
            model_name='pveitem',
            old_name='hoofdstuk',
            new_name='chapter',
        ),
        migrations.RenameField(
            model_name='pveitem',
            old_name='paragraaf',
            new_name='paragraph',
        ),
        migrations.RenameField(
            model_name='pveitem',
            old_name='versie',
            new_name='version',
        ),
        migrations.RenameField(
            model_name='pveonderdeel',
            old_name='naam',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='pveparagraaf',
            old_name='paragraaf',
            new_name='paragraph',
        ),
        migrations.RenameField(
            model_name='pveversie',
            old_name='versie',
            new_name='version',
        ),
        migrations.RenameField(
            model_name='typeobject',
            old_name='versie',
            new_name='version',
        ),
        migrations.RemoveField(
            model_name='itembijlages',
            name='versie',
        ),
        migrations.RemoveField(
            model_name='pvehoofdstuk',
            name='versie',
        ),
        migrations.RemoveField(
            model_name='pveparagraaf',
            name='versie',
        ),
        migrations.RemoveField(
            model_name='pveversie',
            name='belegger',
        ),
        migrations.AddField(
            model_name='itembijlages',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemAttachment', to='app.pveversie'),
        ),
        migrations.AddField(
            model_name='pvehoofdstuk',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapter', to='app.pveversie'),
        ),
        migrations.AddField(
            model_name='pveparagraaf',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paragraph', to='app.pveversie'),
        ),
        migrations.AddField(
            model_name='pveversie',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='version', to='project.beleggers'),
        ),
        migrations.AlterField(
            model_name='itembijlages',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='itemAttachment', to='app.PVEItem'),
        ),
        migrations.AlterField(
            model_name='pvehoofdstuk',
            name='onderdeel',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapter', to='app.pveonderdeel'),
        ),
        migrations.AlterField(
            model_name='pveparagraaf',
            name='hoofdstuk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='paragraph', to='app.pvehoofdstuk'),
        ),
    ]
