# Generated by Django 3.1.12 on 2021-12-08 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20211208_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pveparagraaf',
            old_name='hoofdstuk',
            new_name='chapter',
        ),
    ]
