# Generated by Django 2.2.7 on 2020-04-29 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20200415_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrstatus', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projstatus', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PVEItemAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation', models.TextField(max_length=1000)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PVEItem')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectnaam', models.CharField(max_length=500)),
                ('versienummer', models.CharField(blank=True, max_length=100)),
                ('datum', models.DateField(blank=True)),
                ('printdatum', models.DateField(blank=True)),
                ('acquisiteur', models.CharField(blank=True, max_length=500)),
                ('ontwikkelaar', models.CharField(blank=True, max_length=500)),
                ('leeswijze', models.TextField(blank=True, max_length=5000)),
                ('opmerkingenAqcuisiteur', models.TextField(blank=True, max_length=5000)),
                ('illustratie', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/')),
                ('projectfase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ProjectFase')),
                ('statuscontract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ContractStatus')),
                ('statusproject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ProjectStatus')),
            ],
        ),
        migrations.AddField(
            model_name='pveitem',
            name='projects',
            field=models.ManyToManyField(blank=True, to='app.Project'),
        ),
    ]
