# Generated by Django 3.0.5 on 2020-07-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20200429_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='projectfase',
        ),
        migrations.RemoveField(
            model_name='project',
            name='statuscontract',
        ),
        migrations.RemoveField(
            model_name='project',
            name='statusproject',
        ),
        migrations.RemoveField(
            model_name='pveitemannotation',
            name='item',
        ),
        migrations.AddField(
            model_name='pveitem',
            name='basisregel',
            field=models.BooleanField(default=False),
        ),
    ]
