# Generated by Django 3.0.5 on 2020-07-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('app', '0027_auto_20200714_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pveitem',
            name='projects',
            field=models.ManyToManyField(blank=True, to='project.Project'),
        ),
        migrations.DeleteModel(
            name='ContractStatus',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectFase',
        ),
        migrations.DeleteModel(
            name='ProjectStatus',
        ),
        migrations.DeleteModel(
            name='PVEItemAnnotation',
        ),
    ]
