# Generated by Django 3.0.8 on 2020-07-18 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_project_permission'),
        ('app', '0029_customuser_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='projectpermits',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
    ]
