# Generated by Django 3.0.8 on 2020-07-18 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_userdetails_projectpermits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='projectpermits',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='type',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
