# Generated by Django 3.0.8 on 2021-02-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0036_auto_20210204_1847"),
        ("pvetool", "0012_auto_20210205_2057"),
    ]

    operations = [
        migrations.AddField(
            model_name="frozencomments",
            name="todo_comments",
            field=models.ManyToManyField(
                related_name="todo_comments", to="project.PVEItemAnnotation"
            ),
        ),
    ]
