# Generated by Django 3.1.7 on 2021-02-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pvetool", "0014_commentreply_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentreply",
            name="kostenConsequenties",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=10, null=True
            ),
        ),
    ]
