# Generated by Django 3.1.12 on 2021-10-20 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pvetool', '0017_auto_20211014_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreply',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reply', to='pvetool.commentstatus'),
        ),
    ]
