# Generated by Django 3.1.12 on 2021-12-08 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pvetool', '0018_auto_20211020_1229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentreply',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='bijlagetoreply',
            old_name='bijlage',
            new_name='attachment',
        ),
        migrations.RenameField(
            model_name='bijlagetoreply',
            old_name='naam',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='commentreply',
            old_name='bijlage',
            new_name='attachment',
        ),
        migrations.RenameField(
            model_name='commentreply',
            old_name='kostenConsequenties',
            new_name='consequentCosts',
        ),
        migrations.RenameField(
            model_name='commentreply',
            old_name='datum',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='commentreply',
            old_name='gebruiker',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='gebruikersrang',
            new_name='usersrank',
        ),
        migrations.AlterField(
            model_name='bijlagetoreply',
            name='reply',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='attachmenttoreply', to='pvetool.commentreply'),
        ),
    ]
