# Generated by Django 3.1.12 on 2021-12-14 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0047_auto_20211214_1511'),
        ('pvetool', '0019_auto_20211208_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentreply',
            name='costtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reply', to='project.costtype'),
        ),
    ]
