# Generated by Django 3.1.12 on 2021-12-21 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20211208_1335'),
        ('pvetool', '0020_commentreply_costtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_allowed', models.ManyToManyField(related_name='attachment_allowed', to='pvetool.CommentStatus')),
                ('comment_allowed', models.ManyToManyField(related_name='comment_allowed', to='pvetool.CommentStatus')),
                ('comment_required', models.ManyToManyField(related_name='comment_required', to='pvetool.CommentStatus')),
                ('version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.pveversie')),
            ],
        ),
    ]
