# Generated by Django 4.0.1 on 2022-01-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvetool', '0021_commentrequirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentrequirement',
            name='attachment_required',
            field=models.ManyToManyField(related_name='attachment_required', to='pvetool.CommentStatus'),
        ),
        migrations.AddField(
            model_name='commentrequirement',
            name='costs_allowed',
            field=models.ManyToManyField(related_name='costs_allowed', to='pvetool.CommentStatus'),
        ),
        migrations.AddField(
            model_name='commentrequirement',
            name='costs_required',
            field=models.ManyToManyField(related_name='costs_required', to='pvetool.CommentStatus'),
        ),
    ]
