# Generated by Django 4.0.1 on 2022-01-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvetool', '0022_commentrequirement_attachment_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentrequirement',
            name='attachment_required',
            field=models.ManyToManyField(blank=True, related_name='attachment_required', to='pvetool.CommentStatus'),
        ),
    ]
