# Generated by Django 3.0.8 on 2020-12-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("syntrus", "0007_commentreply_frozencomments"),
    ]

    operations = [
        migrations.AddField(
            model_name="frozencomments",
            name="open",
            field=models.BooleanField(null=True),
        ),
    ]
