# Generated by Django 3.0.8 on 2020-12-09 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syntrus', '0008_frozencomments_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frozencomments',
            name='open',
        ),
    ]
