# Generated by Django 3.1.7 on 2021-08-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syntrus', '0015_commentreply_kostenconsequenties'),
    ]

    operations = [
        migrations.AddField(
            model_name='bijlagetoreply',
            name='naam',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
