# Generated by Django 3.0.5 on 2020-07-14 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0027_auto_20200714_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrstatus', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projstatus', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PVEItemAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation', models.TextField(max_length=1000)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PVEItem')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectnaam', models.CharField(max_length=500)),
                ('versienummer', models.CharField(blank=True, max_length=100)),
                ('datum', models.DateTimeField(blank=True)),
                ('printdatum', models.DateField(blank=True)),
                ('acquisiteur', models.CharField(blank=True, max_length=500)),
                ('ontwikkelaar', models.CharField(blank=True, max_length=500)),
                ('leeswijze', models.TextField(blank=True, max_length=5000)),
                ('opmerkingenAqcuisiteur', models.TextField(blank=True, max_length=5000)),
                ('illustratie', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/')),
                ('projectfase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.ProjectFase')),
                ('statuscontract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.ContractStatus')),
                ('statusproject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.ProjectStatus')),
                ('userspermitted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
