# Generated by Django 3.0.8 on 2020-07-18 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_customuser_userdetails'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='userspermitted',
            new_name='permission',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='versienummer',
            new_name='plaats',
        ),
        migrations.RemoveField(
            model_name='project',
            name='acquisiteur',
        ),
        migrations.RemoveField(
            model_name='project',
            name='illustratie',
        ),
        migrations.RemoveField(
            model_name='project',
            name='leeswijze',
        ),
        migrations.RemoveField(
            model_name='project',
            name='ontwikkelaar',
        ),
        migrations.RemoveField(
            model_name='project',
            name='opmerkingenAqcuisiteur',
        ),
        migrations.RemoveField(
            model_name='project',
            name='printdatum',
        ),
        migrations.RemoveField(
            model_name='project',
            name='projectfase',
        ),
        migrations.RemoveField(
            model_name='project',
            name='projectnaam',
        ),
        migrations.RemoveField(
            model_name='project',
            name='statusproject',
        ),
        migrations.AddField(
            model_name='project',
            name='naam',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='nummer',
            field=models.FloatField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='pensioenfonds',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='vhe',
            field=models.FloatField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='pveitemannotation',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='datum',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pveitemannotation',
            name='annotation',
            field=models.TextField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='pveitemannotation',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.PVEItem'),
        ),
        migrations.DeleteModel(
            name='ProjectFase',
        ),
        migrations.DeleteModel(
            name='ProjectStatus',
        ),
    ]
