# Generated by Django 3.0.8 on 2020-07-18 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20200718_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='permission',
        ),
    ]
