# Generated by Django 3.0.8 on 2020-07-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_auto_20200723_2330"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="plaatsnamen",
            field=models.CharField(default=None, max_length=250),
        ),
    ]
