# Generated by Django 3.0.8 on 2020-07-19 15:16

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_permitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='plaats',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
