# Generated by Django 3.0.8 on 2020-08-06 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_auto_20200723_2330"),
        ("project", "0005_auto_20200806_1706"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="bouwsoort1",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.Bouwsoort",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="bouwsoort2",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="SubBouwsoort",
                to="app.Bouwsoort",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="doelgroep1",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.Doelgroep",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="doelgroep2",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="SubDoelgroep",
                to="app.Doelgroep",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="typeObject1",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.TypeObject",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="typeObject2",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="SubTypeObject",
                to="app.TypeObject",
            ),
        ),
    ]
