# Generated by Django 3.0.8 on 2020-08-14 15:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0006_auto_20200806_1708"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="permitted",
        ),
        migrations.AddField(
            model_name="project",
            name="permitted",
            field=models.ManyToManyField(default=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
