# Generated by Django 3.0.8 on 2020-08-18 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0007_auto_20200814_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='pveitemannotation',
            name='datum',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pveitemannotation',
            name='gebruiker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pveitemannotation',
            name='kostenConsequenties',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10),
        ),
    ]
