# Generated by Django 3.0.8 on 2020-08-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_pveitemannotation_gebruiker'),
    ]

    operations = [
        migrations.AddField(
            model_name='pveitemannotation',
            name='datum',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
