# Generated by Django 3.0.8 on 2020-08-18 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0008_auto_20200818_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pveitemannotation',
            name='kostenConsequenties',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
