# Generated by Django 3.0.8 on 2020-10-05 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0016_pveitemannotation_voldoet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pveitemannotation",
            name="annotation",
            field=models.TextField(default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="pveitemannotation",
            name="gebruiker",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
