# Generated by Django 3.0.8 on 2020-10-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0017_auto_20201005_1835"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pveitemannotation",
            name="voldoet",
            field=models.BooleanField(default=False),
        ),
    ]
