# Generated by Django 3.0.8 on 2020-10-08 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("syntrus", "0006_commentstatus"),
        ("project", "0018_auto_20201005_1922"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pveitemannotation",
            name="voldoet",
        ),
        migrations.AddField(
            model_name="pveitemannotation",
            name="status",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="syntrus.CommentStatus",
            ),
        ),
    ]
