# Generated by Django 3.0.8 on 2020-11-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_auto_20201030_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bijlagetoannotation',
            name='annbijlage',
            field=models.FileField(blank=True, null=True, upload_to='OpmerkingBijlages/'),
        ),
    ]
