# Generated by Django 3.0.8 on 2020-11-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0021_auto_20201103_1437"),
    ]

    operations = [
        migrations.AddField(
            model_name="pveitemannotation",
            name="annbijlage",
            field=models.FileField(
                blank=True, null=True, upload_to="OpmerkingBijlages/"
            ),
        ),
        migrations.DeleteModel(
            name="BijlageToAnnotation",
        ),
    ]
