# Generated by Django 3.0.8 on 2020-11-16 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0024_pveitemannotation_bijlage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bijlagetoannotation',
            old_name='annbijlage',
            new_name='bijlage',
        ),
        migrations.RemoveField(
            model_name='pveitemannotation',
            name='bijlage',
        ),
    ]
