# Generated by Django 3.0.8 on 2020-11-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0025_auto_20201116_1653"),
    ]

    operations = [
        migrations.AddField(
            model_name="pveitemannotation",
            name="bijlage",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
