# Generated by Django 3.0.8 on 2020-11-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0026_pveitemannotation_bijlage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='frozenLevel',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='fullyFrozen',
            field=models.BooleanField(default=False),
        ),
    ]
