# Generated by Django 3.0.8 on 2021-02-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0034_auto_20210125_1808"),
    ]

    operations = [
        migrations.AddField(
            model_name="pveitemannotation",
            name="init_accepted",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
