# Generated by Django 3.1.7 on 2021-08-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0037_project_pve_versie'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='first_annotate',
            field=models.CharField(choices=[('SOG', 'Projectmanager'), ('SD', 'Derde')], default='SOG', max_length=3),
        ),
    ]
