# Generated by Django 3.1.12 on 2021-10-14 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syntrus', '0016_bijlagetoreply_naam'),
        ('users', '0019_forgotpassinvite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0019_auto_20211014_1426'),
        ('project', '0039_bijlagetoannotation_naam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abbonement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soort', models.CharField(blank=True, max_length=255, null=True)),
                ('kosten', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('projectlimiet', models.IntegerField(blank=True, null=True)),
                ('werknemerlimiet', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='pveitemannotation',
            options={'ordering': ['-datum']},
        ),
        migrations.AddField(
            model_name='beleggers',
            name='beheerder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='beleggers',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='KlantLogos'),
        ),
        migrations.AlterField(
            model_name='bijlagetoannotation',
            name='ann',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bijlageobject', to='project.pveitemannotation'),
        ),
        migrations.AlterField(
            model_name='project',
            name='belegger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='project.beleggers'),
        ),
        migrations.AlterField(
            model_name='project',
            name='organisaties',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='project', to='users.Organisatie'),
        ),
        migrations.AlterField(
            model_name='project',
            name='permitted',
            field=models.ManyToManyField(default=None, related_name='projectspermitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectmanager',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectmanager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='pve_versie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='app.pveversie'),
        ),
        migrations.AlterField(
            model_name='project',
            name='statuscontract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='project.contractstatus'),
        ),
        migrations.AlterField(
            model_name='pveitemannotation',
            name='gebruiker',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pveitemannotation',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='annotation', to='app.pveitem'),
        ),
        migrations.AlterField(
            model_name='pveitemannotation',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='annotation', to='project.project'),
        ),
        migrations.AlterField(
            model_name='pveitemannotation',
            name='status',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotation', to='syntrus.commentstatus'),
        ),
        migrations.AddField(
            model_name='beleggers',
            name='abbonement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.abbonement'),
        ),
    ]
