# Generated by Django 3.1.12 on 2021-10-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0040_auto_20211014_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abbonement',
            name='kosten',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
