# Generated by Django 3.1.12 on 2021-10-20 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0021_auto_20211020_1229'),
        ('project', '0041_auto_20211014_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='belegger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='project.beleggers'),
        ),
        migrations.AlterField(
            model_name='project',
            name='bouwsoort1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.bouwsoort'),
        ),
        migrations.AlterField(
            model_name='project',
            name='bouwsoort2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SubBouwsoort', to='app.bouwsoort'),
        ),
        migrations.AlterField(
            model_name='project',
            name='bouwsoort3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SubSubBouwsoort', to='app.bouwsoort'),
        ),
        migrations.AlterField(
            model_name='project',
            name='commentchecker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commentchecker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='doelgroep1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.doelgroep'),
        ),
        migrations.AlterField(
            model_name='project',
            name='doelgroep2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SubDoelgroep', to='app.doelgroep'),
        ),
        migrations.AlterField(
            model_name='project',
            name='doelgroep3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SubSubDoelgroep', to='app.doelgroep'),
        ),
        migrations.AlterField(
            model_name='project',
            name='first_annotate',
            field=models.CharField(choices=[('SOG', 'Projectmanager'), ('SD', 'Stakeholder')], default='SOG', max_length=3),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectmanager',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projectmanager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='pve_versie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='app.pveversie'),
        ),
        migrations.AlterField(
            model_name='project',
            name='statuscontract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='project.contractstatus'),
        ),
        migrations.AlterField(
            model_name='project',
            name='typeObject1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.typeobject'),
        ),
        migrations.AlterField(
            model_name='project',
            name='typeObject2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SubTypeObject', to='app.typeobject'),
        ),
        migrations.AlterField(
            model_name='project',
            name='typeObject3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SubSubTypeObject', to='app.typeobject'),
        ),
        migrations.CreateModel(
            name='BeheerdersUitnodiging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitee', models.EmailField(max_length=254)),
                ('expires', models.DateTimeField()),
                ('key', models.CharField(max_length=100)),
                ('klantenorganisatie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.beleggers')),
            ],
        ),
    ]
