# Generated by Django 3.1.12 on 2021-10-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20211020_1307'),
        ('project', '0042_auto_20211020_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='organisaties',
            field=models.ManyToManyField(blank=True, default=None, related_name='project', to='users.Organisatie'),
        ),
    ]
