# Generated by Django 3.1.12 on 2021-12-03 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pvetool', '0018_auto_20211020_1229'),
        ('project', '0043_auto_20211022_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='pveitemannotation',
            name='firststatus',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_annotation', to='pvetool.commentstatus'),
        ),
    ]
