# Generated by Django 3.1.12 on 2021-12-14 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0046_auto_20211214_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pveitemannotation',
            old_name='costType',
            new_name='costtype',
        ),
    ]
