# Generated by Django 4.0.1 on 2022-02-02 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0047_auto_20211214_1511'),
    ]

    operations = [
        migrations.RenameModel('Beleggers', 'Client'),
        migrations.AlterField(
            model_name='beheerdersuitnodiging',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.client'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='project.client'),
        ),
    ]
