# Generated by Django 4.0.1 on 2022-02-02 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_customuser_client_alter_invitation_client_and_more'),
        ('app', '0027_alter_actieveversie_client_alter_pveversie_client'),
        ('project', '0048_remove_beleggers_beheerder_and_more'),
    ]

    operations = [
    ]
